### ISSUE TITLE
CommandArgs.add(Map) cause BufferOverflowException

### ISSUE THREAD

**Issue by sunnyawake** [wg/lettuce#11]
java.nio.BufferOverflowException
    at java.nio.HeapByteBuffer.put(Unknown Source)
    at com.lambdaworks.redis.protocol.CommandArgs.realloc(CommandArgs.java:175)
    at com.lambdaworks.redis.protocol.CommandArgs.add(CommandArgs.java:63)
    at com.lambdaworks.redis.RedisAsyncConnection.hmset(RedisAsyncConnection.java:318)

**Comment by wg** [comment]
Thanks for the issue report! Could you share the snippet of code, or a minimal test case, that reproduces this Exception?

**Comment by sunnyawake** [comment]
...
Map<String,byte[]> values=new HashMap<String, byte[]>();
values.put("username", username.getBytes(IoUtil.utf8));
values.put("startsession", Buffers.l(System.currentTimeMillis()));
values.put("playerid", Buffers.l(account.playerid));
Redis.hmset("hxsessions:"+token, values);

in Redis setup:
client = new RedisClient(host, port);
async = client.connectAsync(new StringKeyCodec());
sync = client.connect(new StringKeyCodec());

in Rredis.hmset:
async.hmset(key, values);

the map size is three which trigger CommandArgs.realloc:
 public CommandArgs<K, V> add(Map<K, V> map) {
        if (map.size() > 2) {
            realloc(16 \* map.size());
        }

if i change 16 to 17 or some bigger number, no more exceptions.

**Comment by wg** [comment]
Great, thank you! That's a nasty little bug. I've fixed it and released 2.3.1, though the maven central sync may take a little while.
