### ISSUE TITLE
exec without multi times out waiting for a reply instead of throwing Exception

### ISSUE THREAD

**Issue by jencompgeek** [wg/lettuce#14]
Admittedly a bit of a corner case, but I ran into this recently in an integration test. The following code times out after a minute, where I would expect an immediate Exception, as when running "exec" without "multi" from redis-cli.

```
public class TxTest {

    private com.lambdaworks.redis.RedisConnection<byte[], byte[]> txConn;

    @Before
    public void setUp() {
        RedisClient client = new RedisClient("localhost", 6379);
        txConn = new com.lambdaworks.redis.RedisConnection<byte[], byte[]>(client.connectAsync(LettuceUtils.CODEC));
    }

    @Test
    public void testExecWithoutMulti() {
        txConn.exec();
    }

}
```

**Comment by wg** [comment]
Thanks for the issue report @jencompgeek! I've pushed a fix and released 2.3.3 to maven central.
