### ISSUE TITLE
Call to RedisAsyncConnection.awaitAll() hangs after transaction discard

### ISSUE THREAD

**Issue by jencompgeek** [wg/lettuce#18]
Admittedly this is an edge case (why would someone care about results of something that happened in a discarded transaction?). But it's possible at the moment in our API if someone "closes the pipeline" containing results of a discarded transaction. This makes a call to connection.awaitAll() with all the Futures queued since the pipeline was "opened". We don't have the context to know that some are related to discarded transactions (https://github.com/SpringSource/spring-data-redis/blob/master/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L274).

Wondering if anything can be done to avoid us having to track whether or not the Futures are part of a discarded transaction? Maybe an error could be set on the CommandOutputs for all the ops that are part of the discarded transaction? 

```
public class ClientTests {

    private RedisClient client;

    @Before
    public void setUp() {
        this.client =  new RedisClient("localhost", 6379);
    }

    @Test
    public void testMultiDiscard() throws Exception {
        RedisAsyncConnection<byte[], byte[]> conn = client.connectAsync(LettuceUtils.CODEC);
        conn.multi();
        Future<String> results = conn.set("testitnow2".getBytes(), "notok".getBytes());
        conn.discard();
       // This hangs...
        results.get();
    }


}
```

**Comment by wg** [comment]
Hi @jencompgeek, thanks for the suggestion! I agree that the async futures shouldn't stay in limbo on discard, and have just pushed commit 5141640dc8289ff3af07b44a87020cef719c5f4a which marks them completed. This means if get() is called they'll return the default value (null or an empty collection) for that output type.
