### ISSUE TITLE
exec not returning null if a watched key is modified

### ISSUE THREAD

**Issue by jencompgeek** [wg/lettuce#9]
It seems that connection.exec() returns an empty array if a watched key is modified before exec() is called.  According to Redis documentation, "if at least one watched key is modified before the EXEC command, the whole transaction aborts, and EXEC returns a Null multi-bulk reply to notify that the transaction failed." (see http://redis.io/topics/transactions, check-and-set section).

I work on the Spring Data Redis project and noticed this behavior when testing our RedisAtomicInteger.compareAndSet method, which expects connection.exec() to return null if the value was modified by another thread while watched (https://github.com/SpringSource/spring-data-redis/blob/master/src/main/java/org/springframework/data/redis/support/atomic/RedisAtomicInteger.java#L163).

Here's a test that seems to reproduce the behavior.  You should see at least one empty array printed to the console (you may need to run it a few times):

``` java
@Test
public void testCompareSet() throws Exception {
    final CountDownLatch latch = new CountDownLatch(50);
    final RedisClient client = new RedisClient("localhost");
    RedisConnection<String, String> connection = client.connect();
    connection.set("mykey", "1");

    for (int i = 0; i < 50; i++) {
        new Thread(new Runnable() {
            public void run() {
                try {
                    RedisConnection<String, String> connection = client.connect();
                    connection.watch("mykey");
                    if ("1".equals(connection.get("mykey"))) {
                        connection.multi();
                        connection.set("mykey", "2");
                        List ops = connection.exec();
                        System.out.println(ops);
                    }
                } finally {
                    latch.countDown();
                }
            }
        }).start();
    }
    latch.await();
}
```

**Comment by wg** [comment]
Hi @jencompgeek, I think returning an empty List<Object> is the expected behavior of lettuce's implementation of EXEC. I'm guessing that Spring Data Redis was original implemented using a client that returns null instead? I could see a valid argument for either return value, but don't want to break any existing users of lettuce so I'd suggest doing the isEmpty check and convert that to null in https://github.com/SpringSource/spring-data-redis/blob/master/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L459

**Comment by jencompgeek** [comment]
Yep, we can make that change. Just wanted to confirm this was expected
behavior.  Some of the other client implementations we support return null
as they are just returning the null multi-bulk reply from Redis, hence the
assumption in RedisAtomicInteger.

**Comment by wg** [comment]
Great, thanks! It's awesome to see Spring Data Redis supporting lettuce.

**Comment by jencompgeek** [comment]
I finally got around to implementing this change and did run into an issue where this code runs multi/exec with no commands in between. This returns an empty list since there are no results and when that list gets converted to null in LettuceConnection, the code enters an infinite loop.  https://github.com/SpringSource/spring-data-redis/blob/master/src/main/java/org/springframework/data/redis/support/collections/CollectionUtils.java#L71

I'm still planning to implement the change, as I don't think renaming a key that doesn't exist is a common scenario.  However, I thought I'd mention it since it seems to be a valid use case for a semantic difference b/w returning empty list b/c no stmts were issued during a tx and returning it b/c a watched key was modified.
